name: Cypress Parallel Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1, 2, 3]  # Adjust the number of containers as needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version that matches your project's requirements

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests in parallel
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}  # Cypress Dashboard Record Key
        run: |
          npx cypress run --record --parallel --ci-build-id ${{ github.run_id }} --group "Container-${{ matrix.containers }}"
