name: Cypress Test CI

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: cypress-io/github-action@v6
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#         with:
#           browser: chrome
#       - name: Cypress run
#         uses: cypress-io/github-action@v4.2.0 # use the explicit version number
#         with:
#           command: npm run cy:run:ui