name: Cypress Test CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: 20
      - uses: cypress-io/github-action@v6
        with:
            record: true
            working-directory: .
            install: true
            command: npm run cy:run:ui

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: cypress-io/github-action@v6
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#         with:
#           browser: chrome
#       - name: Cypress run
#         uses: cypress-io/github-action@v4.2.0 # use the explicit version number
#         with:
#           command: npm run cy:run:ui