name: Cypress Test CI

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        containers: [1, 2, 3, 4] # Adjust the number based on your parallelization needs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: dependencies
        run: npm install
      - name: Run Cypress tests
        run: |
         npm run cy:run:ui
        #  Use below code to run api tests in parallel
        # run: |
        #  npm run cy:run:ui
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          TERM: xterm

