name: Cypress Test CI

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        containers: [1, 2, 3, 4] # Adjust the number based on your parallelization needs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: dependencies
        run: npm install
      - name: Run Cypress tests
        run: |
         npm run cy:run:ui

      # # Install npm dependencies, cache them correctly
      # # and run all Cypress tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v4
      #   with:
      #     command: npm run cy:run:ui

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: cypress-io/github-action@v6
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#         with:
#           browser: chrome
#       - name: Cypress run
#         uses: cypress-io/github-action@v4.2.0 # use the explicit version number
#         with:
#           command: npm run cy:run:ui